### ISSUE TITLE
Taking minutes for lights to appear in kelvin/ not appearing ever?

### ISSUE THREAD

**Issue by jordanyeo** [stefanwichmann/kelvin#31]
First off, thanks so much for writing this library! It's *exactly* what I'm looking for. I'm hoping you can help me troubleshoot. I've got kelvin running, but some of my lights seem to never be detected or effected by Kelvin. I don't have any issue with my hue switches seeming to control my bulbs instantly, but there is sometimes a few minutes delay for the Kelvin logs report detecting a light. Is this a Kelvin problem, or a hue bridge/zigbee problem? Would love to get your thoughts on where to start troubleshooting- I want this to work so bad!

**Comment by stefanwichmann** [comment]
Hi Jordan,

I'm glad you like Kelvin! Let's try to get it working for you.

First thing to note: 
Delays between a physical action on a lightbulb and the corresponding state of the bridge are usually caused by the zigbee communication. This most often happens if you use a classic power switch to turn your light on and off. In this scenario the bulb will has to "boot up" and establish a connection to the bridge before Kelvin can set a valid state.

If this is your situation I suggest the following troubleshooting steps:

1) Update your bridge and bulbs to the latest firmware (especially the bulbs received an important stability update in November 2017)
2) Experiment with the position of the bridge (Are the affected lights far away? Are the any thick walls between the bridge and the bulbs?)
3) Experiment with the position of the affected bulbs (Does the behaviour change of the bulb sits right next to the bridge?)

Aside from these steps there is not much we can do. Kelvin will poll your bridge every second. This should not be the reason for a long delay. I use physical switches at home and Kelvin usually takes 5-10 seconds to take control.

If your lights don't appear at all you should check the logs:

- Start Kelvin with the "-debug" parameter to get more information.
- Does the light appear in the initial startup listing?
- Is the ID of the affected light associated to any schedule?
- You can use the device name to grep for the relevant log lines.

Hope this helps! Let me know if you got your setup working!

Stefan

**Comment by jordanyeo** [comment]
Thanks for the speedy response! I'm not using classic power switches anywhere, only the Hue remotes.

Some more details- it's not always the same lights that Kelvin doesn't seem to detect. I've got 29 pot lights on my upstairs, and it's not always the same bulbs, or tied to a physical area. It is seemingly random which ones just don't get affected by Kelvin. I've never had delays with my hue remotes being undiscoverable, or not being able to communicate with the bulbs either. I'll run with debug on and see if I can find anything else.

**Comment by stefanwichmann** [comment]
Starting with release v1.1.5 Kelvin will log if a light was switched off or became physically unreachable. I suspect the later to be the problem in your case.

If you find the time please update and have a look at the logs...
