### ISSUE TITLE
Constantly high CPU usage of kelvin on Raspberry Pi Zero

### ISSUE THREAD

**Issue by EmilyBjoerk** [stefanwichmann/kelvin#45]
I just installed Kelvin on a fresh install of Rasbian on a Raspberry Pi Zero W.

When I look at `top` I see that Kelvin is consistently consuming 20% of my CPU all the time. This is much more than expected. I was expecting it to wake up maybe once per minute to adjust lights based on the schedule and go to sleep. 

Is this normal? Is there anything I can do to reduce CPU usage? I was looking for a low power solution.

**Comment by stefanwichmann** [comment]
Hi Emily,

thanks for giving Kelvin a try!

Sadly the observed behavior is normal when using Kelvin. Currently the Hue bridge has no way of informing users that the state of a light changed. So the only way to realize programs like Kelvin is to ask the bridge for changes again and again... Kelvin currently does this *every second for every light*! This is why you see a load of 20%... If I would reduce this polling frequency it would take much longer for Kelvin to become active once you turn on a light.

If you feel adventurous and now a little bit about go you can adjust the polling value here: https://github.com/stefanwichmann/kelvin/blob/master/light.go#L45

If you are just concerned about energy consumption I think you should not worry to much. The Raspberry PI Zero is a low power device by design and the CPU isn't the only component using energy. If you take the memory and the wifi chip into consideration, the 20% shouldn't matter to much.

Nevertheless I would love to see a way for Kelvin to consume less energy while maintaining the same level of service. If you have ideas I am all ears! :-)

**Comment by EmilyBjoerk** [comment]
Anything C++, and I'm your girl but Go... not really :D 

Still, it's a 1 GHz CPU with around 1 IPC so a 20% load for a polling frequency of 1 Hz sounds high to me.

Is there an easy way for me to profile and see where the time is spent? I tried dumping stacks from gdb but that didn't really give much without symbols.

**Comment by stefanwichmann** [comment]
This blog post provides an introduction to go profiling:

https://blog.golang.org/profiling-go-programs

If you feel like it, give it a try! This help would definitely be very welcome. Can't promise a timeline but will also look into it...

**Comment by jpds** [comment]
@stefanwichmann Can we make that light update interval a configurable option? With the 'remember-last-light-state' option in the new firmware update - I don't require my lights to change that much. Also, I have a large number of bulbs at home, to the point where I can't use the mobile app while Kelvin is running.

**Comment by stefanwichmann** [comment]
Just released Kelvin 1.2.0 which should improve the performance a lot! Especially in setups with many lights... Let me know if it works for you!

**Comment by EmilyBjoerk** [comment]
@stefanwichmann I just updated. It seems that CPU usage has dropped from ~20% to ~6% CPU which is a significant improvement. Thanks!
