### ISSUE TITLE
Request: Larger temperature range

### ISSUE THREAD

**Issue by clemenules** [stefanwichmann/kelvin#54]
Ability to set temp from 1000K would be nice.

What is the rationale of not having a larger range of temperatures to choose from? I was guessing because it would break compatibility with some Hue lamps, but then I saw you already made a distinction of possible ranges to ensure compatibility as a result of issue #26 - if I understand correctly.

I'm not a programmer by any means but actually managed to tinker with the source code, added 1000-2000K to the lookup table, changed a few 2000s to 1000 and compiled for ARM and... it's running on my Pi right now and no problems with latest Hue "White and Color Ambiance" bulbs. 

Great if this could be implemented?

**Comment by stefanwichmann** [comment]
Hi clemenules,

as far as I am aware the is currently no hue lamp that physically supports color temperatures lower than 2000K. This is also the lower boundary stated in the official API documentation.

Do you see a visual difference between 1000K and 2000K?

**Comment by clemenules** [comment]
Yup. Much more orange-y / reddish. Not practical for waking hours but we let the lamps fade to 1000K and brightness = 1 in the last interval of the day and this is what is stays at until sunrise. Not sure if we'll keep using 1000K in the long run but definitely sth below 2000K.  

I've seen the documentation you mentioned but I saw in your code you use a lookup table colorspace.go that converts temperatures to corresponding x,y color coordinates. Not sure what the API documentation refers to as in the end the lights get color 'coordinates' and not a K value? I googled the values for 2000K and found a table with the same values that goes down to 1000K and added those (https://github.com/f-spot/f-spot/blob/master/src/Core/FSpot.Cms/CctTable.cs). Works fine.

**Comment by jcbzqy** [comment]
I emulated @clemenules' approach and was able to get color temperatures down to 1000K working as well, on a Windows machine.  However, I do notice that F.lux puts out slightly different hues than Kelvin for low (<2000) temperatures - perhaps the F.lux team has manually adjusted their conversion tables for a more pleasant "yellowish" light.

**Comment by stefanwichmann** [comment]
Ok, i had a look at this and the request seems reasonable.

BUT: Color temperatures lower than 2000k are only supported if we control the lights in "xy mode" (which is what colorspace.go does). When we control lights in "ct mode" (which is the Kelvin default) we can not go lower than 2000k.

If you are interested in the detail you can read about them here:
https://developers.meethue.com/develop/get-started-2/core-concepts/#colors-get-more-complicated

It gets really tricky if you have bulbs from different Hue product lines. For example one "Hue White and Color Ambiance" bulb and one "Hue White Ambiance". The first ones support "xy mode" while the later ones only support "ct mode". All details can be found here: https://developers.meethue.com/develop/hue-api/supported-devices/

In order to support setups with different bulbs I see three options:
1. Use a color range supported by all models (this would be 2000k and is currently implemented)
2. Adapt the lowest common value based on the current setup (If you only have White and Color Ambiance models we could allow to go down to 1000k)
3. Allow 1000k as the new minimum and just stick to 2000k for bulbs that can't go lower

I chose to go with option 1 because it's the most simply, consistent and easiest one to understand. Option 2 is really hard to explain in the documentation (some people don't know the technical specification of their individual bulbs). It could also make your configuration invalid if you later add a White Ambiance bulb to your Color bulb setup. Option 3 would result in bulbs ending up in different color shades which is weird if you have a mix of them in one room.

Any thoughts on this?

**Comment by jcbzqy** [comment]
I vote option 2.

I think the contingent of Hue users who visit GitHub for light control will understand Hue specifications and color space/gamut conversions.

A sample simple explanation:
- "Hue White": Only brightness adjusts, not color
- "Hue White Ambiance": Adjusts in a color temperature range of 2200K (slightly orange, a little warmer than a standard incandescent lamp) to 6500K (overcast daylight)
- "Hue White and Color Ambiance": Can output a wide range of colors. By mapping color temperatures to its input values, color temperatures of as low as 1000K (more or less "red") can be achieved.

**Comment by npwalker** [comment]
I vote option 3.  I have 3 color bulbs, a hue go, 1 ambiance, and 3 white.  generally speaking these are broken apart by room or outside.  However, I have the hue go and an ambiance in one room and even in that case I'd want the go to be more red and the ambiance to be as low as it can.  

If I was concerned with the hue go and the ambiance bulb being the same temperature I could just break out a separate schedule for them that made sure they bottom out at 2000 right?  

I don't like option 2 because it takes away the option of lowering the temperature for bulb that support it when they have other bulbs that don't.  

Option 2 seems like something that would be great for a CLI tool that could detect the bulbs and suggest a configuration based on them but wouldn't necessarily have to be built into the application where you can't edit it post-facto.

**Comment by stefanwichmann** [comment]
Initial testing looks good. I updated the documentation and did some minor improvements/fixes...

Will keep an eye on it and release a new version in a few days.

**Comment by stefanwichmann** [comment]
Released as part of Kelvin 1.3.0
